export type Bike = {
    "id": string,
    "назва": string,
    "виробник": string,
    "тип": string,
    "рама": string,
    "діаметрКолеса": number,
    "розмірРами": string,
    "вилка": string,
    "мотор": string,
    "акамулятор": string,
    "пробіг": string,
    "тип вилки": string,
    "система": string,
    "планетарнаВтулка": string,
    "перемикач задній": string,
    "касета": string,
    "ланцюг": string,
    "манетки": string,
    "гріпси": string,
    "шатуни": string,
    "гальма": string,
    "колеса": string,
    "передняВтулка": string,
    "задняВтулка": string,
    "покришки": string,
    "вага": number,
    "ціна": number,
    "img": string,
    "photo": string[]
}
